# This is a basic workflow to help you get started with Actions

name: simple

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BITL:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v4
      - name: Check out repository code
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: run main script
        run: python ./servo.py

